export const CarStatus = [
  {
    field: 'billLadingId',
    headerName: 'بارنامه',
    cellStyle: {'white-space': 'normal', 'font-size': '12px', 'font-weight': 'bold'},
    maxWidth: 100,
    headerClass: 'bg-indigo-500 text-white',
  },
  {
    field: 'prodNo',
    headerName: 'شماره ساخت',
    cellStyle: {'white-space': 'normal', 'font-size': '12px', 'font-weight': 'bold'},
    autoHeight: true,
    minWidth: 200,
    headerClass: 'bg-indigo-500 text-white',
  },
  {
    field: 'chassisNo',
    headerName: 'شماره شاسی',
    minWidth: 230,
    cellStyle: {'white-space': 'normal', 'font-size': '12px'},
    autoHeight: true,
    headerClass: 'bg-indigo-500 text-white',
  },
  {
    field: 'originDesc',
    headerName: 'مبداء',
    minWidth: 100,
    cellStyle: {'white-space': 'normal', 'font-size': '12px'},
    autoHeight: true,
    headerClass: 'bg-indigo-500 text-white',
  },
  {
    field: 'destinationDesc',
    headerName: 'مقصد',
    minWidth: 100,
    cellStyle: {'white-space': 'normal', 'font-size': '12px'},
    autoHeight: true,
    headerClass: 'bg-indigo-500 text-white',
  },
  {
    field: 'driverName',
    headerName: 'راننده',
    minWidth: 230,
    cellStyle: {'white-space': 'normal', 'font-size': '12px'},
    autoHeight: true,
    headerClass: 'bg-indigo-500 text-white',
  },
  {
    field: 'driverNationalId',
    headerName: 'کدملی راننده',
    minWidth: 230,
    cellStyle: {'white-space': 'normal', 'font-size': '12px'},
    autoHeight: true,
    headerClass: 'bg-indigo-500 text-white',
  },
  {
    field: 'contractorName',
    headerName: 'پیمانکار',
    minWidth: 100,
    cellStyle: {'white-space': 'normal', 'font-size': '12px'},
    autoHeight: true,
    headerClass: 'bg-indigo-500 text-white',
  },
  {
    field: 'traceCreateDate',
    headerName: 'تاریخ',
    minWidth: 200,
    cellStyle: {'white-space': 'normal', 'font-size': '12px'},
    autoHeight: true,
    headerClass: 'bg-indigo-500 text-white',
  },
  {
    field: 'carStatusDesc',
    headerName: 'وضعیت خودرو',
    minWidth: 200,
    cellStyle: {'white-space': 'normal', 'font-size': '12px'},
    autoHeight: true,
    headerClass: 'bg-indigo-500 text-white',
  },
  {
    field: 'carDeliveryStatusDesc',
    headerName: 'وضعیت تحویل',
    minWidth: 150,
    cellStyle: {'white-space': 'normal', 'font-size': '12px'},
    autoHeight: true,
    headerClass: 'bg-indigo-500 text-white',
  },
  {
    field: 'traceDescription',
    headerName: 'توضیحات',
    minWidth: 200,
    // cellRenderer: params => params.data.traceDescription === null ? <span>..............</span> : params.data.traceDescription,
    cellStyle: {'white-space': 'normal', 'font-size': '12px'},
    autoHeight: true,
    headerClass: 'bg-indigo-500 text-white',
  },
]
